### ISSUE TITLE
[Refactor] 코드 리뷰 기반으로 코드 다듬기

### ISSUE THREAD

**Issue by soonitoon** [soonitoon/cmi-react-calendar#20]
4주차 과제를 리뷰 받고 코드를 다듬겠습니다.

## TODO

- [ ] 내용이 없는 리액트 컴포넌트는 닫는 태그 쓰지 않기.
- [ ] `React.FC` 대신 `props`에 대한 타입을 직접 정의하기.
- [ ] `interface`를 정의할 때 변수명에 "I" 프리픽스 붙이지 않기.
- [ ] `Redux`의 `action creator`가 반환하는 액션 타입을 정적으로 만들기.
